apiVersion: v2
name: freescout
description: A Helm chart for Kubernetes
icon: https://freescout.net/apple-touch-icon.png
maintainers:
  - name: Zoran Zorica
    email: zzorica@soultrace.net
type: application
version: 1.0.1
appVersion: "2.2.10"
dependencies:
  - name: mariadb
    version: ~11.x
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
