{{- $adminToken := "" }}
{{- if and (eq .Values.admin.enabled true) (not .Values.admin.existingSecret) }}
{{- $adminToken = .Values.admin.token | default (randAlphaNum 48) | b64enc | quote }}
{{- end -}}

{{- $smtpUser := "" }}
{{- if and (eq .Values.smtp.enabled true ) (not .Values.smtp.existingSecret) (.Values.smtp.user) }}
{{- $smtpUser = .Values.smtp.user | b64enc | quote }}
{{- end -}}

{{- if or (ne $adminToken "") (ne $smtpUser "" ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
data:
  {{- if ne $adminToken "" }}
  admin-token: {{ $adminToken }}
  {{- end }}
  {{- if ne $smtpUser "" }}
  smtp-user: {{ $smtpUser }}
  smtp-password: {{ required "Must specify SMTP password" .Values.smtp.password | b64enc | quote }}
  {{- end }}
{{- end }}
