{{- if or (not .Values.mariadb.enabled) .Values.externalDatabase.enabled }}
{{- if not .Values.externalDatabase.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "db"  }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: {{ include "freescout.name" . }}
    helm.sh/chart: {{ include "freescout.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if not (empty .Values.externalDatabase.password) }}
  db-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- else }}
  db-password: {{ required "A External Database Password is required!" .Values.externalDatabase.password }}
  {{- end }}
{{- end }}
{{- end }}
