name: Release Charts

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'charts/**/README.md'
      - 'LICENSE'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          helm_version: 3.22.0
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
          charts_url: https://charts.soultrace.net
          branch: gh-pages
          target_dir: charts
          index_dir: .
